apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - name: puma
          image: kalelc/demo-puma:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/log
              name: app-storage
              subPath: log
            - mountPath: /app/public
              name: app-storage
              subPath: public
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
            - containerPort: 3000
        - name: nginx
          image: kalelc/demo-nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/log
              name: app-storage
              subPath: log
            - mountPath: /app/public
              name: app-storage
              subPath: public
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "20m"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pv-claim
