apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - name: puma
          image: kalelc/puma
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-storage
              mountPath: /app/sockets
        - name: nginx
          image: kalelc/nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: app-storage
              mountPath: /app/sockets
      volumes:
        - name: app-storage
          emptyDir: {}
