apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - name: puma
          image: kalelc/demo-puma:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/sockets
              name: app-socket
            - mountPath: /app/log
              name: app-storage
              subPath: logs
            - mountPath: /app/public/assets
              name: app-storage
              subPath: assets
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
        - name: nginx
          image: kalelc/demo-nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/sockets
              name: app-socket
            - mountPath: /app/public/assets
              name: app-storage
              subPath: assets
          resources:
            limits:
              cpu: "50m"
            requests:
              cpu: "20m"
      volumes:
        - name: app-socket
          emptyDir: {}
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pv-claim
