kind: PersistentVolume
apiVersion: v1
metadata:
  name: app-storage-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: app-storage
  capacity:
    storage: 10Gi
  awsElasticBlockStore:
    volumeID: vol-0f6a35f8ec976ec67
    fsType: ext4
